services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - homeassistant:/config
      #- /mnt/emmc/downloads:/media/music:ro
    restart: unless-stopped
    networks:
      - ha-net
    ports:
      - "8000:8123"
    environment:
      - TZ=Asia/Phnom_Penh
volumes:
  homeassistant:
    external: true

networks:
  ha-net:
    name: ha-net
    driver: bridge
