name: immich

services:
  immich-server:
    container_name: immich-app

    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload:rw
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - TZ=Asia/Phnom_Penh
      - DISABLE_ML=true
    networks:
      - immich-net
    depends_on:
      - redis
      - database
    restart: unless-stopped
    healthcheck:
      disable: false
    ports:
      - "2000:2283"

 # immich-machine-learning:
 #   container_name: immich_machine_learning
 #   image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
 #   volumes:
 #     - model_cache:/cache
 #     - ${UPLOAD_LOCATION}:/usr/src/app/upload
 #   env_file:
 #     - .env
 #   restart: always
 #   networks:
 #     - immich-net
 #   devices:
 #     - /dev/dri:/dev/dri
 #   healthcheck:
 #     disable: false


  redis:
    container_name: immich-redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped
    networks:
      - immich-net

  database:
    container_name: immich-db
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:8d292bdb796aa58bbbaa47fe971c8516f6f57d6a47e7172e62754feb6ed4e7b0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      TZ: Asia/Phnom_Penh
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data:rw
    shm_size: 128mb
    restart: unless-stopped
    networks:
      - immich-net


networks:
  immich-net:
    name: immich-net
    driver: bridge
