services:
  yt-dlp-webui:
    image: marcobaobao/yt-dlp-webui:latest
    #image: ghcr.io/marcopiovanello/yt-dlp-web-ui:latest
    container_name: yt-dlp
    environment:
      - YTDLP_EXTRA_OPTS=--extract-audio --audio-format mp3 --audio-quality 192
      - TZ=Asia/Phnom_Penh
    ports:
      - 8020:3033
    volumes:
      - /mnt/emmc/downloads:/downloads # replace <your dir> with a directory on your host system
      - ./config:/config    # directory where config.yml will be stored
    healthcheck:
      test: curl -f http://localhost:3033 || exit 1
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
