services:
  actual-server:
    image: actualbudget/actual-server:latest
    container_name: actual-budget
    volumes:
      - /mnt/emmc/budget/:/data:rw
    networks:
      - budget-net
    ports:
      - '2020:5006'
    restart: unless-stopped
    # pull_policy: always  # Uncomment only if your Compose version supports it
    environment:
      - TZ=Asia/Phnom_Penh
networks:
  budget-net:
    name: budget-net
    driver: bridge
