services:
  docmost:
    container_name: docmost-app
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: '${APP_URL}'
      APP_SECRET: '${APP_SECRET}'
      DATABASE_URL: 'postgresql://docmost:${DOCMOST_URL}@db:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
      TZ: Asia/Phnom_Penh
      MAIL_DRIVER: smtp
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 465
      SMTP_SECURE: true
      SMTP_USERNAME: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASS}
      MAIL_FROM_ADDRESS: ${SMTP_USER}
      MAIL_FROM_NAME: Docmost
    networks:
      - docmost-net
    ports:
      - "2010:3000"
    restart: unless-stopped
    volumes:
      - /mnt/emmc/docmost/docmost_app:/app/data/storage:rw
  db:
    container_name: docmost-db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: ${POSTGRES_DB}
      TZ: Asia/Phnom_Penh
    restart: unless-stopped
    networks:
      - docmost-net
    volumes:
      - /mnt/emmc/docmost/docmost_db:/var/lib/postgresql/data:rw

  redis:
    container_name: docmost-redis
    image: redis:7.2-alpine
    restart: unless-stopped
    networks:
      - docmost-net

networks:
  docmost-net:
    name: docmost-net
    driver: bridge 
