services:
  adguard-h1:
    container_name: adguard-h1
    image: adguard/adguardhome:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Asia/Phnom_Penh
    volumes:
      - adguard_data:/opt/adguardhome/work
      - adguard_data:/opt/adguardhome/conf
volumes:
  adguard_data:
    external: true
